### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Ezharjan** [perseus784/Vehicle_Collision_Prediction_Using_CNN-LSTMs#3]
How to cite this work?
Thanks!

**Comment by perseus784** [comment]
Hi, thanks for asking.
I have now added the citation to github repository. You can find "Cite this repository" option on the right side pane for any citation format that you want.

**Comment by Ezharjan** [comment]
> Hi, thanks for asking. I have now added the citation to github repository. You can find "Cite this repository" option on the right side pane for any citation format that you want.

Thanks!
